### ISSUE TITLE
Error updating status: 0, message='Attempt to decode JSON

### ISSUE THREAD

**Issue by YOminae** [captainmustard/Icecast2DiscordBot#1]
When you follow the installation steps and run it, it sends the following message infinitely and the bot does not work.

Error updating status: 0, message='Attempt to decode JSON with unexpected mimetype: text/xml

Is this script functional or is it a test prototype?
Is the project active or abandoned?

**Comment by insseyn** [comment]
config.yaml needs the good icecast_status_url. Icecast provides an url to check the mount-points: "http://<server_address>/status-json.xsl". But it doesn't work if we don't specify the channel. If we suppose that  the channel url is "http://<serveur_address:port>/radio.mp3", then the url needed would be "http://<server_address:port>/status-json.xls?mount=/radio.mp3". (This should be explained in the Readme, I spend hours to find that url.)
However I don't manage to make the bot working. I fill config.yaml correctly I think, the bot connects to discord, it displays the current track but it does'nt connect to the vocal room. I checked the room'ID several times in config.yaml, the value is correct. Maybe a right trouble ? I try to run the bot with admin rights with no result.
Thank you for reading. 
1nss3yn

**Comment by captainmustard** [comment]
It was just a small thing I whipped up in an hour. Haven't used it in several months. I'll take a look though. Kind of surprised anyone else ever tried it.

**Comment by captainmustard** [comment]
Okay i've updated the script and it should both work and be easier to use now

- removed the need to supply he status-json url. It'll figure that out on it's own now from the stream url

- added required library to requirements.txt for discord.py to connect to voice channels

- the bot will now join the voice channel without the user having to leave and re-enter

- if the status page doesn't supply artist / track metadata, the bot will fall back to some other alternatives before finally just settling on displaying the hostname of the icecast server
